### ISSUE TITLE
Avoid cloning the PDU payload just to comptue its length

### ISSUE THREAD

**Issue by xpromache** [ASU-cubesat/cfdp-rs#13]
In several places but especially when computing the size of the file data PDUs, the code will do a clone followed by an encode:
https://github.com/ASU-cubesat/cfdp-rs/blob/main/cfdp-core/src/transaction/send.rs#L293

after which the Vec<u8> result is only used to take its length and then it is dropped.

Instead, the PDUPayload should have a method encoded_len(file_size_flag: FileSizeFlag) and return the length without encoding anything if possible.

For  PDUs which are rarely sent and small in size (that is all except the file data) it can internally still do  self.encode().len() but for the data PDUs it can optimize by just using the data length to compute the payload length.

**Comment by mkolopanis** [comment]
This has been on my radar too. Thanks for the suggestions, I think that's a good way to at least get the clone out of the file data for now. it could easily be extended later if desired.
