### ISSUE TITLE
PDUTransport is_ready() usage

### ISSUE THREAD

**Issue by xpromache** [ASU-cubesat/cfdp-rs#35]
Hello,

(sorry for the absence, I was busy finishing some other stuff but now I'm back on CFDP)

What is the intent behind the PDUTransport is_ready method ?

It does not seem to be used anywhere.

**Comment by mkolopanis** [comment]
Welcome back!

It's been on my mind, should just be removed. I think it was a carry over when I was using the python version for inspiration.
