### ISSUE TITLE
remove the terminate signal passed to the Daemon

### ISSUE THREAD

**Issue by xpromache** [ASU-cubesat/cfdp-rs#38]
Hello, I suggest some more cleanup: currently there is a terminate signal passed to the daemon in the new method. That signal is passed by the daemon to the transport and never read back by the daemon (except in my pull request where I only check it to print an warning message).

So effectively when the user sets that signal, it will terminate the transport  rather than the daemon. To terminate the daemon, the user can simply close the user_primitive channel.

As a first step, I suggest we eliminate the terminate signal from the interface between the user and the daemon. The signal can be created in the Daemon::new instead.

As a second step we may wonder if the signal between the daemon and the transport is actually necessary at all. The daemon has a channel towards the transport and can  close (drop) the channel to signal termination.

**Comment by mkolopanis** [comment]
Sounds like a plan. I don't think the terminate is necessary really. I've been getting a lot more familiar with using empty channels as termination signals myself. I think it'll be cleaner to move the code in that direction.
