### ISSUE TITLE
PDUTransport::send_pdu not used?

### ISSUE THREAD

**Issue by xpromache** [ASU-cubesat/cfdp-rs#39]
The PDUTransport trait requires a method send_pdu but that method is not used anywhere in the daemon or transaction code. In the implementations of the trait, the method is called from the pdu_handler.

I think send_pdu can be safely removed from the trait definition.

**Comment by mkolopanis** [comment]
This is probably true. I think originally I used it to separate the sending and receiving ideas. Give myself a more atomized structure, but in the end the only real method should be the `pdu_handler`

**Comment by mkolopanis** [comment]
I've had another idea regarding the transports. Could re-work the trait to have a required "send_pdu" and "recv_pdu" method. Then provide a default method for the "pdu_handler" method.

**Comment by xpromache** [comment]
That is an idea indeed. 
But I suggest we make first the change to async and then we change further the transport.
