### ISSUE TITLE
Fine-tunning the NAK procedure

### ISSUE THREAD

**Issue by xpromache** [ASU-cubesat/cfdp-rs#48]
Hello,

I've implemented a transport which sends PDUs via two paths with slightly different latencies. That causes the PDUs to become unordered when received by the CFDP receiver. When immediate NAK procedure is used, the receiver will generate a NAK for each such unordered PDU even though the PDU is in transit and will arrive shortly. This in turn causes a lot of unneeded retransmissions.

Similarly, when the EOF is received (for both NAK procedures), the receiver may see that the last PDU has not been received and send a NAK  even though that PDU is in transit and will arrive shortly.

To fix this issue, I propose to add two parameters to the NAK procedure definition:
```
pub enum NakProcedure {
    Immediate(delta_verification: u64, delay_verification: Duration),
    Deferred( delay_verification: Duration),
}
```

The ``delta_verification: u64`` parameter will be used as a delta for the missing data verification: when receiving a FileDataPdu (offset, len), instead of verifying if any data is missing in the [0, offset) interval, we will verify the [0, offset-delta_verification) interval. If delta=0 then the current behavior will be kept.

The second ``delay_verification: Duration`` parameter will be used to postpone the NAK verification after the reception of the EOF. If it is 0 then the verification will not be delayed and the current behavior will be kept.

Because the ``delta_verification`` is much easier to implement than the ``delay_verification`` and will eliminate the great majority of the unneeded retransmissions, I will start with it. I will also add some statistics on the sender to keep track of how many retransmissions have been performed.

**Comment by mkolopanis** [comment]
Sounds interesting but I want to make sure I understand fully. 
In the `delta_verification`, could we ever end up in a state where a NAK is never created for missing data. Imagine in your scenario if one of the PDUs is dropped instead of just re-ordered. Would the `delta_verification` forget about it entirely or are you imagining that the `get_all_naks` after EoF has been received will always behave with `delta_verification = 0`?

**Comment by xpromache** [comment]
Let's imagine that we split the file in chunks 1 to n, and the receiver receives chunk number 10. It looks in the history and it sees that the chunks 3, 6 and 9 are missing (also chunks 11 - n are missing but those are in the future so they don't count). In the current implementation it immediately sends a NAK(3,6,9). My proposal is to introduce a parameter delta_verification, let's use delta_verification=5. When the receiver receives chunk 10, it will for the missing chunks in the range 1-5, so it will send a NAK(3) ignoring the missing chunks 6 and 9.
But then when it will receive chunk 11, it will look at 1-6 so if 6 is still missing, it will send a NAK(6). Chances are however that 6 was actually on the pipe (coming via the slower link) so may have been received by the time 11 arrived on the fast link.

When the receiver receives the EOF, it follows the current procedure sending NAK for all missing chunks. For the EOF I imagined the other parameter delay_verification which will cause the checking for missing chunks to happen a little bit after the EOF has been received such that any pending PDU on the slow link had time to arrive (assuming the EOF came on the fast link).

(we work with file offsets rather than chunk numbers but the principle is the same)

I'm talking here about milliseconds difference in latency, not minutes or hours, so those parameters will be quite small and can cause no noticeable increase of total file transfer time. By avoiding systematic NAK generation, they may actually improve substantially the transfer time.

**Comment by mkolopanis** [comment]
Yeah I think that answers my main question. thanks for providing the example. If you'd like to implement this I like it.
