### ISSUE TITLE
CFDP Sender Flow Control

### ISSUE THREAD

**Issue by xpromache** [ASU-cubesat/cfdp-rs#9]
Currently the CFDP Sender uses an unbounded channel towards the transport which causes all the data of the file to be queued in the channel, waiting to be sent by the transport. This is clearly not a good strategy:
- in case of a large file, one can easily run out of memory. 
- inactivity timeouts may trigger although data is being transferred.
- multiple EOFs may be issued and queued in the channel although the receiver did not get a chance to receive even the first one

We assume that the transport controls the flow - that means the transport can issue PDUs at whatever speed is available on the underlying network and the sender has to comply (backpressure). Transferring data even at a slow rate should not trigger inactivity timeouts. 

To implement this, the channel between the sender and the transport should be bounded - ideally of size 0 (for performance reasons - to be benchmarked! - we may allow the size be greater than 0).

The problem with bounded channels is that any send operation may block - that means the sender will have to send only when it knows the operation will not block - that is after a Select returned info that the channel is writable.
This also means that any send operation that is currently performed upon receiving a PDU (for example the FIN ACK sent upon reception of FIN PDU) will have to be removed.

In order to facilitate that I propose to introduce a clearer state machine in the sender - it can be inspired from this:
https://public.ccsds.org/Pubs/720x2g3ec1s.pdf 
Table 5-3

There is already a general TransactionState - my newly introduced state will be a substate for the active transactions. It will replace the current "waiting_on" field.

Note: same can be done for the receiver but I focus on the sender first to eliminate the problems mentioned above.

**Comment by mkolopanis** [comment]
Ah that state table reminds me a lot of the python implementation https://gitlab.com/librecube/lib/python-cfdp. 
I was wondering where that was based on, since this kind of design is not mentioned in the current implementer's guide.
https://public.ccsds.org/Pubs/720x2g4.pdf

But like you mentioned this current implementation already ended up with a `WaitingOn` State that it tracks. Might just be easier in the long run to do this.

**Comment by xpromache** [comment]
Interesting is that in Yamcs I ended up with a state diagram a bit similar to the document without actually seeing  the document. I only discovered the doc now, after you told me about the python cfdp and I've seen a reference there.

I will get some inspiration from it but certainly I will not implement all those EXY events.
